# Required files, scripts and programs {-}

## Programs {-}

- seqkit v2.1 ([website](https://bioinf.shenwei.me/seqkit/))
	- Installed via Bioconda ([link](https://bioconda.github.io/recipes/seqkit/README.html))
	- Base environment needs to be activated in order to use the tool
	
- RDP tool classifier v2.11 ([Github](https://github.com/rdpstaff/classifier) / [SourceForge](https://sourceforge.net/projects/rdp-classifier/))
  - To install the RDP classifier I recommend downloading the package from SourceForge as the Github is no longer maintained. Once the download is complete, unzip the folder and locate the file `classifer.jar` inside the directory `dist`
  
- usearch v11.0.667 ([website](http://www.drive5.com/usearch/))
  - To install : (1) Download binaries (2) Unzip and rename the file to `usearch` (3) Make file executable `chmod +x usearch`. Place file in an easily accessible directory (for example `~/usearch`)
  
- vsearch v2.15.2 ([Github](https://github.com/torognes/vsearch))
  - Installed via Bioconda ([link](https://anaconda.org/bioconda/vsearch))
  - Base environment needs to be activated in order to use the tool

## Databases {-}

The following databases can be downloaded with following the hyperlinks. 

- [COI formatted for Barque](https://www.ibis.ulaval.ca/services/bioinformatique/barque_databases/)
- [Eukaryote CO1 Classifier for RDP V5.1](https://github.com/terrimporter/CO1Classifier/releases/tag/RDP-COI-v5.1.0) 
- [12S fish Classifier v1.0.1](https://github.com/terrimporter/12SfishClassifier/releases/tag/v1.0.1)
- [12S formatted for barque](https://github.com/enormandeau/barque/blob/master/03_databases/12S.fasta.gz)

## Scripts {-}

In order to train the RDP classifier on any database the following scripts are required and can be found [here](https://github.com/karinevilleneuve/fish_eDNA/tree/master/scripts). 

- lineage2taxTrain.py
- addFullLineage.py
