# Supplementary data {-}

## Installing the RDP classifier {-}

The RDP Classifier is a naive Bayesian classifier that provides rapid and accurate taxonomic placement of rRNA gene sequences. 

1. Download the 

RDPTools is a collection fo command-line tools written by the RDP staff at Michigan State University. 
More information and tutorials on how to install, use and retrain RDP Clasifier can be found on at https://github.com/rdpstaff/classifier and John Quensen's blog (https://john-quensen.com/).



Unfortunately, the The RDP website is no longer available and therefore the packages must be installed using the Docker verison of RDPTools. instruction where obtained from Dr. J.Quensen's [Website](https://jfq3.gitbook.io/rdptools-docker).

1. Installing Docker Engine 

The following installation instruction were obtained directly from the [Docker documentation page](https://docs.docker.com/engine/install/ubuntu/)
```{bash, eval = FALSE}
# --------------------- Run the following command to uninstall all conflicting packages ------------------------
for pkg in docker.io docker-doc docker-compose docker-compose-v2 podman-docker containerd runc; do sudo apt-get remove $pkg; done

# --------------------- Add Docker's official GPG key ------------------------
sudo apt-get update
sudo apt-get install ca-certificates curl
sudo install -m 0755 -d /etc/apt/keyrings
sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
sudo chmod a+r /etc/apt/keyrings/docker.asc

# ------------------------ Add the repository to Apt sources ------------------------
echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
  $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
  sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
sudo apt-get update

# ------------------------ Install the Docker packages ------------------------
sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

# ------------------------ Confirm if installation was successful ------------------------
sudo docker run hello-world
```

2. Creating the container 

To display all locally available docker images : `sudo docker images`

```{bash, eval = FALSE}
sudo docker pull rdpstaff/rdp_tools
```

Containers must be map to a directory outside of the container in order to make results accessible to other programs. In this case I chose the directory `/home/kvilleneuve/rdp_tools/`
```{bash, eval = FALSE}
sudo docker run --name rdp_tools -it -v /home/kvilleneuve/rdp_tools/ rdpstaff/rdp_tools
```

After entering the above command the prompt terminal should be similar to this : `RDPuser@1041715dcc7f:~$`

3. Installing auxiliary programs and files 

Change to root user. Password (`RDPuser`)
```{bash, eval = FALSE}
sudo su - 
``` 

```{bash, eval = FALSE}
# Download script for downloading packages 
wget https://github.com/jfq3/RDPTools-Docker/raw/main/downloads/download_tools_jq.py
# NOTE !!! The script contains a few typo, notable a missing parenthesis and open tick at line 58 !!!! 
# Make script executable 
chmod 750 download_tools_jq.py
# Execute 
python3 download_tools_jq.py
``` 

Log out, exit the container and close the terminal : `exit exit exit`

To launch docker 
```{bash, eval = FALSE}
sudo docker start rdp_tools
sudo docker attach rdp_tools
```
