--- 
title: "Fish eDNA"
author: "Karine Villeneuve"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib]
biblio-style: apalike
link-citations: yes
github-repo: rstudio/bookdown-demo
description: ""
---
# Our dataset {-}

I was given the following dataset of fastq files which were generated by (1) collecting 18 water samples from rivers and lakes near oil-sands extraction site in the province of Alberta, Canada (see map below), (2) filtering the water samples, (3) extracting the DNA collected on the filer, and (4) sequencing the extracted DNA. For each sample collected, two different marker genes were used to amplify and sequence distinct DNA regions : the **12S** ribosomal RNA gene and the mitochondrial cytochrome oxidase subunit (**COI**). 

**Amplified regions details**

| Marker   | Names    | Forward primer sequence     | Reverse primer sequence     | Fragment size (bp)   | Source   |
| -------- | -------- | --------------------------- | --------------------------- | -------------------- | -------- |
| 12S      | MiFish-U | CCGGTAAAACTCGTGCCAGC        | CATAGTGGGGTATCTAATCCCAGTTTG | 247                  | DOI:[10.1111/mec.14395](https://doi.org/10.1111/mec.14395) |
| COI      | COI-PS1  | CGTATTTGGYGCYTGRGCCGGRATAGT | CARAARCTYATRTTRTTYATTCG     | 163-158              | DOI:[10.1098/rsos.150088](https://doi.org/10.1098/rsos.150088) |
